# Generated by Django 5.0 on 2024-01-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.IntegerField()),
                ('ename', models.CharField(max_length=20)),
                ('eemail', models.EmailField(max_length=254)),
                ('eno', models.IntegerField()),
            ],
        ),
    ]
